apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: 955865924758.dkr.ecr.eu-central-1.amazonaws.com/pythontestapp:333db6fcdec793081faea450d3f16dac3eee6bfc
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: python-app
